MeetingManagerMvc/Controllers/CartClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    [Authorize]
    public class CartClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;

        public CartClientController(IConfiguration configuration)
        {
            var http = new HttpWebClient(configuration);
            client = http.GetClient();
            WebApiPath = http.GetWebApiPath();
        }

        [HttpGet]
        public async Task<IActionResult> Confirm(int id)
        {
            HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + id);
            Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

            LineItemModel lineItemModel = new()
            {
                Offer = offert,
                From = DateTime.Today,
                To = DateTime.Today.AddDays(1)
            };

            return View(lineItemModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(int offerId, [Bind("From,To")] LineItemModel lineItem)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            try
            {
                HttpResponseMessage cartResponse = await client.GetAsync(WebApiPath + "Carts/" + identity.Value);
                Cart cart = await cartResponse.Content.ReadAsAsync<Cart>();

                HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + offerId);
                Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

                if (cartResponse.IsSuccessStatusCode)
                {
                    lineItem.Price = offert.Price;
                    lineItem.Name = offert.Title;
                    lineItem.CartId = cart.Id;
                    lineItem.OfferId = offert.Id;

                    HttpResponseMessage cartLineItemResponse = await client.PostAsJsonAsync(WebApiPath + "CartLineItems/", lineItem);
                    cartLineItemResponse.EnsureSuccessStatusCode();

                    return Redirect("/CartClient/Index/");
                }
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }

            return Redirect("/");
        }

        public async Task<IActionResult> Index()
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            HttpResponseMessage cartResponse = await client.GetAsync(WebApiPath + "Carts/" + identity.Value);
            Cart cart = await cartResponse.Content.ReadAsAsync<Cart>();

            List<CartLineItem> lineItems = null;
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetByCardId/" + cart.Id);

            lineItems = await response.Content.ReadAsAsync<List<CartLineItem>>();

            return View(lineItems);
        }

        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetCartLineItem/" + id);
            
            if (response.IsSuccessStatusCode)
            {

                try
                {
                    CartLineItem lineItem = await response.Content.ReadAsAsync<CartLineItem>();

                    HttpResponseMessage deelteRespone = await client.DeleteAsync(WebApiPath + "CartLineItems/" + lineItem.Id);
                    response.EnsureSuccessStatusCode();

                    return Redirect("/CartClient/Index");
                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, int notUsed = 0)
        {
            try
            {
                HttpResponseMessage response = await client.DeleteAsync(WebApiPath + "CartLineItems/" + id);
                response.EnsureSuccessStatusCode();

                return Redirect("/CartClient/Index");
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }
        }

        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetCartLineItem/" + id);
            if (response.IsSuccessStatusCode)
            {
                CartLineItem cartLineItem = await response.Content.ReadAsAsync<CartLineItem>();
                return View(cartLineItem);
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, CartLineItem cartLineItem)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + cartLineItem.OfferId);
                Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

                cartLineItem.TotalPrice = (decimal)(((cartLineItem.To - cartLineItem.From).Days) * offert.Price);

                HttpResponseMessage response = await client.PutAsJsonAsync(WebApiPath + "CartLineItems/" + cartLineItem.Id, cartLineItem);
                response.EnsureSuccessStatusCode();

                return RedirectToAction(nameof(Index));
            }

            return View(cartLineItem);
        }
    }
}

MeetingManagerMvc/Controllers/DashboardClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    public class DashboardClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;

        public DashboardClientController(IConfiguration configuration)
        {
            var http = new HttpWebClient(configuration);
            client = http.GetClient();
            WebApiPath = http.GetWebApiPath();
        }

        [Authorize]
        public async Task<IActionResult> Index([FromQuery] string status)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            int userId = Int32.Parse(identity.Value);
            List<Offer> offers = null;
            HttpResponseMessage response = await client.GetAsync(WebApiPath + $"Offers/OwnerOffers/{userId}?offerStatus={status}");
            if (response.IsSuccessStatusCode)
            {
                offers = await response.Content.ReadAsAsync<List<Offer>>();
            }

            return View(offers);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }
            int userId = Int32.Parse(identity.Value);
            HttpResponseMessage response = await client.GetAsync(WebApiPath + $"Offers/OwnerOffers/{userId}");
            if (response.IsSuccessStatusCode)
            {
                Offer offer = await response.Content.ReadAsAsync<Offer>();
                return View(offer);

            }

            return Redirect("/DashboardClient");
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Id,Title,Description,Price,Status")] Offer offer)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }
            int userId = Int32.Parse(identity.Value);
            HttpResponseMessage response = await client.PutAsJsonAsync(WebApiPath + "Offers/" + id, offer);
            if (response.IsSuccessStatusCode)
            {
                return Redirect("/DashboardClient");
            }

            return Redirect("/DashboardClient");
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(MeetingManagerMvc.Models.CreateOfferModel model)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            if (ModelState.IsValid)
            {
                int userId = Int32.Parse(identity.Value);

                model.UserId = userId;
                HttpResponseMessage response = await client.PostAsJsonAsync(WebApiPath + "Offers", model);

                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Offer has been created!";
                        return LocalRedirect("/");
                    }
                    else
                    {
                        ViewBag.Message = "Provided values is not valid.";
                        return View(model);
                    }
                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }
            }
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Offers/" + id);

            if (response.IsSuccessStatusCode)
            {
                Offer offer = await response.Content.ReadAsAsync<Offer>();
                return View(offer);

            }

            return LocalRedirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Delete(int id, [Bind("")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                
                    HttpResponseMessage response = await client.DeleteAsync(WebApiPath + "Offers/" + id);
                    response.EnsureSuccessStatusCode();

                    return LocalRedirect("/");
            }

            return View(offer);
        }
    }
}

MeetingManagerMvc/Controllers/OrderClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Models;
using MeetingManagerMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    [Authorize]
    public class OrderClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;

        public OrderClientController(IConfiguration configuration)
        {
            var http = new HttpWebClient(configuration);
            client = http.GetClient();
            WebApiPath = http.GetWebApiPath();
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetCartLineItem/" + id);
            CartLineItem cartLineItem = await response.Content.ReadAsAsync<CartLineItem>();

            HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + cartLineItem.OfferId);
            Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

            NewOrderModel newOrder = new()
            {
                Offer = offert,
                CartLineItem = cartLineItem,
                Comment = ""
            };

            return View(newOrder);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int id, [Bind("Offert,Comment,CartLineItem")] NewOrderModel newOrderModel)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            try
            {
                HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetCartLineItem/" + id);
                CartLineItem cartLineItem = await response.Content.ReadAsAsync<CartLineItem>();

                HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + cartLineItem.OfferId);
                offertResponse.EnsureSuccessStatusCode();

                Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

                newOrderModel.Offer = offert;
                newOrderModel.CartLineItem = cartLineItem;
                newOrderModel.UserId = identity.Value;

                HttpResponseMessage orderResponse = await client.PostAsJsonAsync(WebApiPath + "Orders/", newOrderModel);
                orderResponse.EnsureSuccessStatusCode();

                HttpResponseMessage deleteLineItemReponse = await client.DeleteAsync(WebApiPath + "CartLineItems/" + cartLineItem.Id);
                var order = await orderResponse.Content.ReadAsAsync<Order>();

                return Redirect("/Home/ThankYou/" + order.Id);
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }

            return Redirect("/");
        }


        public async Task<IActionResult> List([FromQuery] string status)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Orders/GetOrdersByUserId/" + Int16.Parse(identity.Value) + "?orderStatus="+status);

            List<Order> orders = null;
            if (response.IsSuccessStatusCode)
            {
                orders = await response.Content.ReadAsAsync<List<Order>>();
            }

            return View(orders);
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                HttpResponseMessage response = await client.GetAsync(WebApiPath + "Orders/" + id);

                if (response.IsSuccessStatusCode)
                {
                    Order order = await response.Content.ReadAsAsync<Order>();
                    order.Status = "Canceled";
                    order.EditDate = DateTime.Now;

                    HttpResponseMessage editResponse = await client.PutAsJsonAsync(WebApiPath + "Orders/" + id, order);
                    response.EnsureSuccessStatusCode();

                    return Redirect("/OrderClient/List");
                }

                return NotFound();
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }
        }

        public async Task<ActionResult> OrderDetail(int id)
        {
            try
            {
                HttpResponseMessage orderResponse = await client.GetAsync(WebApiPath + "Orders/" + id);

                if (orderResponse.IsSuccessStatusCode)
                {
                    var order = await orderResponse.Content.ReadAsAsync<Order>();

                    HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + order.OfferId);
                    offertResponse.EnsureSuccessStatusCode();

                    var offert = await offertResponse.Content.ReadAsAsync<Offer>();

                    OrderDetailModel orderDetail = new()
                    {
                        Order = order,
                        Offert = offert
                    };

                    return View(orderDetail);
                }

                return Redirect("/Home/Error");
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }
        }
    }
}

MeetingManagerMvc/Views/OrderClient/Create.cshtml
@model MeetingManager.Models.NewOrderModel

@{
    ViewData["Title"] = "Create";
}


<section class="contact_area section_gap">
    <div class="container">
        <div class="row justify-content-center align-items-center flex-column">
            <div class="col-sm-12" style="text-align:center;">
                <h2 class="title_color">Confirm data below before create an order!</h2>
                <p>Already here...</p>
            </div>
        </div>
        <div class="row confirm-add-to-cart-row">
            <div class="col-sm-8">
                <div class="confirm-reservation-offert">
                    <div class="confirm-reservation-offert-image-add">
                        <img src="~/image/vacation.png" alt="create_order" />
                    </div>
                    <div class="confirm-reservation-text">
                        <h3 style="padding-left:25px; padding-top:25px;">@Html.DisplayFor(model => model.Offer.Title)</h3>
                        <p style="padding-left:25px;">Description: @Model.Offer.Description </p>
                        <p style="padding-left:25px;">From: @Model.CartLineItem.From.ToString("d") | To: @Model.CartLineItem.To.ToString("d")</p>
                        <p style="padding-left:25px;">Total price: <b>@Model.CartLineItem.TotalPrice</b></p>
                    </div>
                </div>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Comment" class="control-label"></label>
                        <input asp-for="Comment" class="form-control" />
                        <span asp-validation-for="Comment" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="Offer" value="@Model.Offer" />
                    <input type="hidden" asp-for="CartLineItem" value="@Model.CartLineItem" />
                    <div class="form-group" style="text-align:center;">
                        <input type="submit" value="Create" class="btn theme_btn button_hover" />
                        <a asp-controller="CartClient" asp-action="Index" class="btn button_hover theme_btn_two">Back to List</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

MeetingManagerMvc/Views/OrderClient/List.cshtml
@model IEnumerable<MeetingManager.Models.Order>

@{
    ViewData["Title"] = "Order list";

    string userId = "";
    string currStatus = Context.Request.Query["status"];
    string allStyles = "background-color: #f3c300;", draftStyles = "", publishedStyles = "", archivedStyles = "";
    if (currStatus == "Saved")
    {
        draftStyles = "background-color: black;";
    }
    else if (currStatus == "Created")
    {
        publishedStyles = "background-color: black;";
    }
    else if (currStatus == "Canceled")
    {
        archivedStyles = "background-color: black;";
    }
    else
    {
        allStyles = "background-color: black;";
        draftStyles = "background-color: #f3c300;";
        publishedStyles = "background-color: #f3c300;";
        archivedStyles = "background-color: #f3c300;";
    }

    foreach (var claim in User.Claims)
    {
        if (claim.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
        {
            userId = claim.Value;
        }
    }
}

<section class="contact_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <nav class="nav nav-borders mb-3" style="border-bottom: 1px solid lightgray;">
                    <a asp-controller="UserDetailClient" asp-action="Index" class="nav-link">Profile</a>
                    <a asp-controller="OrderClient" asp-action="List" asp-route-id="@userId" class="nav-link active">Orders </a>
                    <a asp-controller="DashboardClient" asp-action="Index" class="nav-link">Offers</a>
                </nav>
            </div>
            <div class="col-lg-12 d-flex justify-content-between">
                <div>
                    <a href="/OrderClient/List/@userId" class="btn theme_btn button_hover" style="@allStyles">All</a>
                    <a href="/OrderClient/List/@userId?status=Saved" class="btn theme_btn button_hover" style="@draftStyles">Saved</a>
                    <a href="/OrderClient/List/@userId?status=Created" class="btn theme_btn button_hover" style="@publishedStyles">Open</a>
                    <a href="/OrderClient/List/@userId?status=Canceled" class="btn theme_btn button_hover" style="@archivedStyles">Cancelled</a>
                </div>
            </div>
        </div>


        <div class="row mt-3 justify-content-center align-items-center flex-column"> 
            <div class="col-lg-8 col-sm-10">
                @if (Model.Count() != 0)
        {
                @foreach (var item in Model)
            {
                <div class="cart-line-item">
                    @if (item.To < DateTime.Now)
                    {
                    <p class="order-status s-saved">Saved</p>
                    }

                    else if (item.Status == "Canceled")
                    {
                    <p class="order-status s-canceld">Cancelled</p>
                    }

                    else if (item.Status == "Created")
                    {
                    <p class="order-status s-open">Open</p>
                    }

                    <h3>Order no. #@item.Id</h3>
                    <p>From: @item.From.ToString("d") | To: @item.To.ToString("d")</p>
                    <p>Total costs: @item.Amount</p>
                    <a asp-action="OrderDetail" asp-route-id="@item.Id" class="btn theme_btn button_hover">Details</a>
                    @if (item.Status == "Created" && item.To > DateTime.Now)
                    {
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn custom-danger danger-hover">Cancel <i class="fas fa-ban"></i></a>
                    }
                </div>
            }
        }
        else
        {
                <div class="col-lg-12 mt-4">
                    <p>You don't have any order yet! <a asp-controller="CartClient" asp-action="Index">Please finish your reservations in your cart!</a></p>
                </div>
        }
            </div>
        </div>

    </div>
</section>

MeetingManagerMvc/Views/OrderClient/OrderDetail.cshtml
@model MeetingManagerMvc.Models.OrderDetailModel

@{
    ViewData["Title"] = "Reservation Details";
}

<section class="accomodation_area section_gap">
    <div class="container">
        @{if (Model != null)
            {
                DateTime expiredDate = Model.Order.To.AddDays(1);

                <div class="section_title text-center">
                    <h2 class="title_color">Order details for order no. <b>#@Model.Order.Id</b></h2>
                    <p>
                        We hope you are satisfied with our services!
                    </p>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <p>
                            @if (Model.Order.To < DateTime.Now)
                            {
                                <span class="order-status s-saved">Saved</span>
                            }

                            else if (Model.Order.Status == "Canceled")
                            {
                                <span class="order-status s-canceld">@Model.Order.Status</span>
                            }

                            else if (Model.Order.Status == "Created")
                            {
                                <span class="order-status s-open">Open</span>
                            }
                        </p>
                        <p>
                            @if (Model.Order.EditDate != new DateTime())
                            {
                                <span>Edited: @Model.Order.EditDate</span>
                            }

                            else if (Model.Order.To < DateTime.Now)
                            {
                                <span>Expired: @expiredDate.ToString("d")</span>
                            }
                        </p>
                            <br />
                            <hr />
                            <div class="new-order-offert-details">
                                <div class="new-order-offert-details-image">
                                    <img src="~/image/offer_placeholder.jpg" alt="offer-small" />
                                </div>
                                <div class="new-order-offert-details-text">
                                    <h5>@Model.Offert.Title</h5>
                                    <p>Description: @Model.Offert.Description</p>
                                </div>
                            </div>
                            <br />
                            <p>
                                Reservations dates :
                                <span>Arrival: @Model.Order.From.ToString("d")</span> | <span>Leave: @Model.Order.To.ToString("d")</span>
                            </p>
                            @if (Model.Order.Comment != "" && Model.Order.Comment != null)
                            {
                                <p>Comment: @Model.Order.Comment</p>
                            }
                            <p>Bill: <b>@Model.Order.Amount</b></p>
                        </div>
                </div>
                <div class="col col-sm-12" style="display:flex; justify-content: center; margin-top: 100px">
                    <a asp-controller="OrderClient" asp-action="List" class="button_hover theme_btn_two">Back to list!</a>
                </div>
            }
        }
    </div>
</section>