MeetingManagerMvc/Controllers/DashboardClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    public class DashboardClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;

        public DashboardClientController(IConfiguration configuration)
        {
            var http = new HttpWebClient(configuration);
            client = http.GetClient();
            WebApiPath = http.GetWebApiPath();
        }

        [Authorize]
        public async Task<IActionResult> Index([FromQuery] string status)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            int userId = Int32.Parse(identity.Value);
            List<Offer> offers = null;
            HttpResponseMessage response = await client.GetAsync(WebApiPath + $"Offers/OwnerOffers/{userId}?offerStatus={status}");
            if (response.IsSuccessStatusCode)
            {
                offers = await response.Content.ReadAsAsync<List<Offer>>();
            }

            return View(offers);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }
            int userId = Int32.Parse(identity.Value);
            HttpResponseMessage response = await client.GetAsync(WebApiPath + $"Offers/OwnerOffers/{userId}");
            if (response.IsSuccessStatusCode)
            {
                Offer offer = await response.Content.ReadAsAsync<Offer>();
                return View(offer);

            }

            return Redirect("/DashboardClient");
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Id,Title,Description,Price,Status")] Offer offer)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }
            int userId = Int32.Parse(identity.Value);
            HttpResponseMessage response = await client.PutAsJsonAsync(WebApiPath + "Offers/" + id, offer);
            if (response.IsSuccessStatusCode)
            {
                return Redirect("/DashboardClient");
            }

            return Redirect("/DashboardClient");
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(MeetingManagerMvc.Models.CreateOfferModel model)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            if (ModelState.IsValid)
            {
                int userId = Int32.Parse(identity.Value);

                model.UserId = userId;
                HttpResponseMessage response = await client.PostAsJsonAsync(WebApiPath + "Offers", model);

                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Offer has been created!";
                        return LocalRedirect("/");
                    }
                    else
                    {
                        ViewBag.Message = "Provided values is not valid.";
                        return View(model);
                    }
                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }
            }
            return View(model);
        }

        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Offers/" + id);

            if (response.IsSuccessStatusCode)
            {
                Offer offer = await response.Content.ReadAsAsync<Offer>();
                return View(offer);

            }

            return LocalRedirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Delete(int id, [Bind("")] Offer offer)
        {
            if (ModelState.IsValid)
            {
                
                    HttpResponseMessage response = await client.DeleteAsync(WebApiPath + "Offers/" + id);
                    response.EnsureSuccessStatusCode();

                    return LocalRedirect("/");
            }

            return View(offer);
        }
    }
}

MeetingManagerMvc/Controllers/OrderClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Models;
using MeetingManagerMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    [Authorize]
    public class OrderClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;

        public OrderClientController(IConfiguration configuration)
        {
            var http = new HttpWebClient(configuration);
            client = http.GetClient();
            WebApiPath = http.GetWebApiPath();
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetCartLineItem/" + id);
            CartLineItem cartLineItem = await response.Content.ReadAsAsync<CartLineItem>();

            HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + cartLineItem.OfferId);
            Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

            NewOrderModel newOrder = new()
            {
                Offer = offert,
                CartLineItem = cartLineItem,
                Comment = ""
            };

            return View(newOrder);
        }

        [HttpPost]
        public async Task<IActionResult> Create(int id, [Bind("Offert,Comment,CartLineItem")] NewOrderModel newOrderModel)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            try
            {
                HttpResponseMessage response = await client.GetAsync(WebApiPath + "CartLineItems/GetCartLineItem/" + id);
                CartLineItem cartLineItem = await response.Content.ReadAsAsync<CartLineItem>();

                HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + cartLineItem.OfferId);
                offertResponse.EnsureSuccessStatusCode();

                Offer offert = await offertResponse.Content.ReadAsAsync<Offer>();

                newOrderModel.Offer = offert;
                newOrderModel.CartLineItem = cartLineItem;
                newOrderModel.UserId = identity.Value;

                HttpResponseMessage orderResponse = await client.PostAsJsonAsync(WebApiPath + "Orders/", newOrderModel);
                orderResponse.EnsureSuccessStatusCode();

                HttpResponseMessage deleteLineItemReponse = await client.DeleteAsync(WebApiPath + "CartLineItems/" + cartLineItem.Id);
                var order = await orderResponse.Content.ReadAsAsync<Order>();

                return Redirect("/Home/ThankYou/" + order.Id);
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }

            return Redirect("/");
        }


        public async Task<IActionResult> List([FromQuery] string status)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Orders/GetOrdersByUserId/" + Int16.Parse(identity.Value) + "?orderStatus="+status);

            List<Order> orders = null;
            if (response.IsSuccessStatusCode)
            {
                orders = await response.Content.ReadAsAsync<List<Order>>();
            }

            return View(orders);
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                HttpResponseMessage response = await client.GetAsync(WebApiPath + "Orders/" + id);

                if (response.IsSuccessStatusCode)
                {
                    Order order = await response.Content.ReadAsAsync<Order>();
                    order.Status = "Canceled";
                    order.EditDate = DateTime.Now;

                    HttpResponseMessage editResponse = await client.PutAsJsonAsync(WebApiPath + "Orders/" + id, order);
                    response.EnsureSuccessStatusCode();

                    return Redirect("/OrderClient/List");
                }

                return NotFound();
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }
        }

        public async Task<ActionResult> OrderDetail(int id)
        {
            try
            {
                HttpResponseMessage orderResponse = await client.GetAsync(WebApiPath + "Orders/" + id);

                if (orderResponse.IsSuccessStatusCode)
                {
                    var order = await orderResponse.Content.ReadAsAsync<Order>();

                    HttpResponseMessage offertResponse = await client.GetAsync(WebApiPath + "Offers/" + order.OfferId);
                    offertResponse.EnsureSuccessStatusCode();

                    var offert = await offertResponse.Content.ReadAsAsync<Offer>();

                    OrderDetailModel orderDetail = new()
                    {
                        Order = order,
                        Offert = offert
                    };

                    return View(orderDetail);
                }

                return Redirect("/Home/Error");
            }
            catch (Exception exception)
            {
                return Redirect("/Home/Error");
            }
        }
    }
}

MeetingManagerMvc/Controllers/UserDetailClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    [Authorize]
    public class UserDetailClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;
        private readonly IConfiguration _configuration;

        public UserDetailClientController(IConfiguration configuration)
        {
            _configuration = configuration;
            WebApiPath = _configuration["MeetingManager:Url"];
            client = new HttpClient();
            client.DefaultRequestHeaders.Add("ApiKey", _configuration["MeetingManager:ApiKey"]);
        }

        // GET: UserDetailClient/5
        public async Task<ActionResult> Index(int userId)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();
            if (identity == null)
            {
                return Redirect("/");
            }

            HttpResponseMessage response = await client.GetAsync(WebApiPath + "UsersDetail/" + identity.Value);
            if (response.IsSuccessStatusCode)
            {
                UserDetail detail = await response.Content.ReadAsAsync<UserDetail>();
                return View(detail);
            }

            return NotFound();
        }

        // GET: UserClientController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "UsersDetail/" + id);
            if (response.IsSuccessStatusCode)
            {
                UserDetail userDetail = await response.Content.ReadAsAsync<UserDetail>();
                return View(userDetail);
            }
            return NotFound();
        }

        // POST: UserClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("UserDetailId,Name,SecondName,LastName,Address,City,Region,Country,PostCode,Phone,UserId")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await client.PutAsJsonAsync(WebApiPath + "UsersDetail/" + userDetail.UserId, userDetail);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Index));
            }

            return View(userDetail);
        }
    }
}

MeetingManagerMvc/Views/DashboardClient/Create.cshtml
@model MeetingManagerMvc.Models.CreateOfferModel

@{
    ViewData["Title"] = "Create";
}

<section class="contact_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title_color">Create offer</h2>
            </div>
            <div class="col-md-12">
                <form class="row contact_form" method="post">
                    <div class="col-md-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control" name="Description" id="Description" rows="1" placeholder="Description"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Status" class="control-label"></label>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" class="btn-check" name="Status" id="draft" value="draft" autocomplete="off" checked> Create as draft
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" class="btn-check" name="Status" id="published" value="published" autocomplete="off"> Create published offer
                            </label>
                        </div>

                        <div class="form-group">
                            <label asp-for="Price" class="control-label"></label>
                            <input type="number" asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <button type="submit" value="submit" class="btn theme_btn button_hover">Create offer</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-12">
                <a asp-action="Index" class="button_hover theme_btn_two">Back to List</a>
            </div>
        </div>
    </div>
</section>

MeetingManagerMvc/Views/DashboardClient/Delete.cshtml
@model MeetingManager.Models.Offer;

@{
    ViewData["Title"] = "Delete Offer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="contact_area section_gap">
    <div class="container">
        <div class="row justify-content-center align-items-center flex-column">
            <div class="col-sm-12">
                <h2 class="title_color">Delete offer</h2>
                <p>Are you sure to delete offer @Html.DisplayFor(model => model.Title) with id: @Html.DisplayFor(model => model.Id)?</p>
            </div>
            <div class="col-sm-12">
                <form asp-action="Delete">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @if (!string.IsNullOrEmpty(ViewBag.Message))
                    {
                        <span class="text-danger">
                            @ViewBag.Message
                        </span>
                    }
                    <div class="form-group">
                        <button type="submit" value="submit" class="btn theme_btn button_hover">Confirm</button>
                    </div>
                </form>
            </div>
            <div class="col-sm-12">
                <a class="link" asp-controller="DashboardClient" asp-action="Index">Back to dachboard</a>
            </div>
        </div>
    </div>
</section>

MeetingManagerMvc/Views/DashboardClient/Edit.cshtml
@model MeetingManager.Models.Offer

@{
    ViewData["Title"] = "Edit Offer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="contact_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title_color">Edit offer</h2>
            </div>
            <div class="col-md-12">
                @if (Model != null)
                {
                <form class="row contact_form" method="post">
                    <div class="col-md-12">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control" name="Description" id="Description" rows="1" placeholder="Description"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Status" class="control-label"></label>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" asp-for="Status" class="btn-check" name="Status" id="draft" value="draft" autocomplete="off"> Save as draft
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" asp-for="Status" class="btn-check" name="Status" id="published" value="published" autocomplete="off"> Publish offer
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input type="radio" asp-for="Status" class="btn-check" name="Status" id="archived" value="archived" autocomplete="off"> Archive offer
                            </label>
                        </div>

                        <div class="form-group">
                            <label asp-for="Price" class="control-label"></label>
                            <input type="number" asp-for="Price" class="form-control" />
                            <span asp-validation-for="Price" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input asp-for="Id" type="hidden" class="form-control" />
                            <input asp-for="UserId" type="hidden" class="form-control" />
                        </div>
                        <div class="form-group">
                            <button type="submit" value="submit" class="btn theme_btn button_hover">Edit offer</button>
                        </div>
                    </div>
                </form>
                }
            </div>
            <div class="col-md-12">
                <a asp-controller="DashboardClient" asp-action="Index" class="button_hover theme_btn_two">Back to List</a>
            </div>
        </div>
    </div>
</section>

MeetingManagerMvc/Views/DashboardClient/Index.cshtml
@model IEnumerable<MeetingManager.Models.Offer>

@{
    string userId = "";

    ViewData["Title"] = "Client Offers";
    string currStatus = Context.Request.Query["status"];
    string allStyles = "background-color: #f3c300;", draftStyles = "", publishedStyles = "", archivedStyles = "";
    if (currStatus == "draft")
    {
        draftStyles = "background-color: black;";
    }
    else if (currStatus == "published")
    {
        publishedStyles = "background-color: black;";
    }
    else if (currStatus == "archived")
    {
        archivedStyles = "background-color: black;";
    }
    else
    {
        allStyles = "background-color: black;";
        draftStyles = "background-color: #f3c300;";
        publishedStyles = "background-color: #f3c300;";
        archivedStyles = "background-color: #f3c300;";
    }

    foreach (var claim in User.Claims)
    {
        if (claim.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
        {
            userId = claim.Value;
        }
    }

    string SetStatusBadge(string status)
    {
        if (status == "published")
        {
            return "s-saved";
        }
        else if (status == "draft")
        {
            return "s-open";
        }
        else if (status == "archived")
        {
            return "s-canceld";
        }
        return "warning";
    }
}

<section class="accomodation_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <nav class="nav nav-borders mb-3" style="border-bottom: 1px solid lightgray;">
                    <a asp-controller="UserDetailClient" asp-action="Index" class="nav-link">Profile</a>
                    <a asp-controller="OrderClient" asp-action="List" asp-route-id="@userId" class="nav-link">Orders </a>
                    <a asp-controller="DashboardClient" asp-action="Index" class="nav-link active">Offers</a>
                </nav>
            </div>
            <div class="col-lg-12 d-flex justify-content-between">
                <div>
                    <a href="/DashboardClient" class="btn theme_btn button_hover" style="@allStyles">All</a>
                    <a href="/DashboardClient?status=draft" class="btn theme_btn button_hover" style="@draftStyles">Draft</a>
                    <a href="/DashboardClient?status=published" class="btn theme_btn button_hover" style="@publishedStyles">Published</a>
                    <a href="/DashboardClient?status=archived" class="btn theme_btn button_hover" style="@archivedStyles">Archived</a>
                </div>
                <div>
                    <a asp-controller="DashboardClient" asp-action="Create" class="btn theme_btn button_hover">Create Offer</a>
                </div>
            </div>
        </div>

        <div class="row mb_30 justify-content-center">
            @if (Model != null)
            {
                @if (Model.Count() > 0)
                {
                    @foreach (var item in Model)
                    {
                            <div class="col-lg-8 col-sm-10 mt-3">
                                <div class="cart-line-item d_flex align-items-center">
                                    <img class="img-fluid" style="width: 80px;" src="~/image/offer_placeholder.jpg" alt="img">
                                    <div class="about_content ml-2">
                                        <div class="d-flex justify-content-between align-items-center">
                                            <h2 class="title title_color mb-0" style="font-size:20px;">Offer no. #@item.Id</h2>
                                            <span class="order-status @SetStatusBadge(@item.Status) p-0 m-0 d-flex justify-content-center align-items-center" style="text-transform: uppercase; font-weight:600;height:30px;">@item.Status</span>
                                        </div>
                                        <p class="p-0">Created at: @item.CreatedAt.ToString("d") | Updated at: @item.UpdatedAt.ToString("d")</p>
                                        <p class="p-0">@item.Description</p>
                                        <a asp-controller="DashboardClient" asp-action="Edit" asp-route-id="@item.Id" class="btn theme_btn button_hover" style="background-color: black;">Edit</a>
                                        <a asp-controller="DashboardClient" asp-action="Delete" asp-route-id="@item.Id" class="btn theme_btn button_hover" style="background-color: red;">Delete</a>
                                    </div>
                                </div>
                            </div>
                    }
                }
                else
                {
                    <div class="col-lg-12 mt-4">
                        <p>You don't have any offers with these requirements. You can add them by going to this url</p>
                    </div>
                }

            }
        </div>
    </div>
</section>