MeetingManagerMvc/Controllers/OfferClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Models;
using MeetingManagerMvc.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    public class OfferClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;

        public OfferClientController(IConfiguration configuration)
        {
            var http = new HttpWebClient(configuration);
            client = http.GetClient();
            WebApiPath = http.GetWebApiPath();
        }

        public async Task<IActionResult> Index([FromQuery] string minPrice, [FromQuery] string maxPrice, [FromQuery] string offerTitle)
        {
            List<Offer> offers = null;
            HttpResponseMessage response = await client.GetAsync(WebApiPath + $"Offers?minPrice={minPrice}&maxPrice={maxPrice}&offerTitle={offerTitle}");
            if (response.IsSuccessStatusCode)
            {
                offers = await response.Content.ReadAsAsync<List<Offer>>();
            }

            return View(offers);
        }

        public async Task<IActionResult> Details(int id)
        {

            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Offers/" + id);
            if (response.IsSuccessStatusCode)
            {
                Offer offer = await response.Content.ReadAsAsync<Offer>();
                return View(offer);
            }

            return Redirect("/OfferClient");
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(MeetingManagerMvc.Models.CreateOfferModel model)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();

            if (identity == null)
            {
                return Redirect("/");
            }

            if (ModelState.IsValid)
            {
                int userId = Int32.Parse(identity.Value);

                model.UserId = userId;
                HttpResponseMessage response = await client.PostAsJsonAsync(WebApiPath + "Offers", model);

                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "Offer has been created!";
                        return Redirect("/");
                    }
                    else
                    {
                        ViewBag.Message = "Provided values is not valid.";
                        return View(model);
                    }
                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }
            }
            return View(model);
        }
    }
}

MeetingManagerMvc/Controllers/UserClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using BC = BCrypt.Net.BCrypt;


namespace MeetingManagerMvc.Controllers
{
    public class UserClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;
        private readonly IConfiguration _configuration;

        public UserClientController(IConfiguration configuration)
        {
            _configuration = configuration;
            WebApiPath = _configuration["MeetingManager:Url"];
            client = new HttpClient();
            client.DefaultRequestHeaders.Add("ApiKey", _configuration["MeetingManager:ApiKey"]);
        }


        // GET: UserClientController
        public async Task<ActionResult> Index()
        {
            List<User> users = null;
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "/Users");
            if (response.IsSuccessStatusCode)
            {
                users = await response.Content.ReadAsAsync<List<User>>();
            }
            return View(users);
        }

        public IActionResult RegistryUser(string ReturnUrl = "/")
        {
            UserRegistryModel registryModel = new()
            {
                ReturnUrl = ReturnUrl
            };

            return View(registryModel);
        }

        // POST: UserClientController/RegistryUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegistryUser([Bind("UserName, EmailAddress, Password, RepeatPassword")] UserRegistryModel registryUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (registryUser.Password == registryUser.RepeatPassword)
                    {
                        User user = new()
                        {
                            UserName = registryUser.UserName,
                            EmailAddress = registryUser.EmailAddress,
                            Password = registryUser.Password,
                        };

                        HttpResponseMessage response = await client.PostAsJsonAsync(WebApiPath + "Users", user);
                        response.EnsureSuccessStatusCode();

                        return Redirect("/UserClient/LoginUser");
                    }
                    else
                    {
                        ViewBag.Message = "Inserted passwords doesn't match";
                        return View(registryUser);
                    }

                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }
            }

            return View(registryUser);
        }

        public IActionResult LoginUser(string ReturnUrl = "/")
        {
            LoginModel loginModel = new()
            {
                ReturnUrl = ReturnUrl
            };

            return View(loginModel);
        }

        // POST: UserClientController/LoginUser
        [HttpPost]
        public async Task<IActionResult> LoginUser([Bind("EmailAddressOrUserName,Password,RememberLogin,ReturnUrl")] LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await client.PostAsJsonAsync(WebApiPath + "Users/LoginUser", loginModel);

                try
                {
                    if (response.IsSuccessStatusCode)
                    {
                        var user = await response.Content.ReadAsAsync<User>();

                        var claims = new List<Claim>() {
                            new Claim(ClaimTypes.Name, user.UserName == null ? "" : user.UserName),
                            new Claim(ClaimTypes.Email, user.EmailAddress == null ? "" : user.EmailAddress),
                            new Claim(ClaimTypes.NameIdentifier, user.Id.ToString())
                        };

                        var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var principal = new ClaimsPrincipal(identity);
                        await HttpContext.SignInAsync(
                           CookieAuthenticationDefaults.AuthenticationScheme,
                           principal,
                           new AuthenticationProperties() { IsPersistent = loginModel.RememberLogin }
                        );

                        return LocalRedirect(loginModel.ReturnUrl);
                    }
                    else
                    {
                        ViewBag.Message = "Provided credential is not valid.";
                        return View(loginModel);
                    }
                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }

            }

            return View(loginModel);
        }

        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return LocalRedirect("/");
        }

        // GET: UserClientController/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Users/" + id);
            if (response.IsSuccessStatusCode)
            {
                User user = await response.Content.ReadAsAsync<User>();

                UserRegistryModel registerUser = new()
                {
                    UserName = user.UserName,
                    EmailAddress = user.EmailAddress
                };

                return View(registerUser);
            }
            return NotFound();
        }

        // POST: UserClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Edit(int id, [Bind("UserName,EmailAddress,Password,RepeatPassword")] UserRegistryModel registerUser)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (registerUser.Password == registerUser.RepeatPassword)
                    {
                        User user = new()
                        {
                            Id = id,
                            UserName = registerUser.UserName,
                            EmailAddress = registerUser.EmailAddress,
                            Password = BC.HashPassword(registerUser.Password),
                        };

                        HttpResponseMessage response = await client.PutAsJsonAsync(WebApiPath + "Users/" + id, user);
                        response.EnsureSuccessStatusCode();

                        return Redirect("/UserDetailClient/Index");
                    }
                    else
                    {
                        ViewBag.Message = "Inserted passwords doesn't match";

                        return View(registerUser);
                    }
                }
                catch (Exception exception)
                {
                    return Redirect("/Home/Error");
                }
                
            }

            return View(registerUser);
        }

        // GET: UserClientController/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "Users/" + id);
            if (response.IsSuccessStatusCode)
            {
                User user = await response.Content.ReadAsAsync<User>();

                UserRegistryModel deleteUserModel = new()
                {
                    UserName = user.UserName,
                    Password = user.Password,
                    EmailAddress = user.EmailAddress,
                    RepeatPassword = ""
                };

                return View(deleteUserModel);
            }

            return NotFound();
        }

        // POST: UserClientController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Delete(int id, [Bind("UserName,EmailAddress,RepeatPassword,Password")] UserRegistryModel deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (BC.Verify(deleteUser.RepeatPassword, deleteUser.Password))
                {
                    HttpResponseMessage response = await client.DeleteAsync(WebApiPath + "Users/" + id);
                    response.EnsureSuccessStatusCode();
                    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                    return LocalRedirect("/");
                }
                else
                {
                    ViewBag.Message = "Wrong password was provided try again!";

                    return View(deleteUser);
                }
            }

            return View(deleteUser);
        }
    }
}

MeetingManagerMvc/Controllers/UserDetailClientController.cs
using MeetingManager.Models;
using MeetingManagerMvc.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MeetingManagerMvc.Controllers
{
    [Authorize]
    public class UserDetailClientController : Controller
    {
        private readonly HttpClient client;
        private readonly string WebApiPath;
        private readonly IConfiguration _configuration;

        public UserDetailClientController(IConfiguration configuration)
        {
            _configuration = configuration;
            WebApiPath = _configuration["MeetingManager:Url"];
            client = new HttpClient();
            client.DefaultRequestHeaders.Add("ApiKey", _configuration["MeetingManager:ApiKey"]);
        }

        // GET: UserDetailClient/5
        public async Task<ActionResult> Index(int userId)
        {
            var identity = User.Claims.Where(e => e.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier").FirstOrDefault();
            if (identity == null)
            {
                return Redirect("/");
            }

            HttpResponseMessage response = await client.GetAsync(WebApiPath + "UsersDetail/" + identity.Value);
            if (response.IsSuccessStatusCode)
            {
                UserDetail detail = await response.Content.ReadAsAsync<UserDetail>();
                return View(detail);
            }

            return NotFound();
        }

        // GET: UserClientController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            HttpResponseMessage response = await client.GetAsync(WebApiPath + "UsersDetail/" + id);
            if (response.IsSuccessStatusCode)
            {
                UserDetail userDetail = await response.Content.ReadAsAsync<UserDetail>();
                return View(userDetail);
            }
            return NotFound();
        }

        // POST: UserClientController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, [Bind("UserDetailId,Name,SecondName,LastName,Address,City,Region,Country,PostCode,Phone,UserId")] UserDetail userDetail)
        {
            if (ModelState.IsValid)
            {
                HttpResponseMessage response = await client.PutAsJsonAsync(WebApiPath + "UsersDetail/" + userDetail.UserId, userDetail);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Index));
            }

            return View(userDetail);
        }
    }
}

MeetingManagerMvc/Views/UserDetailClient/Edit.cshtml
@model MeetingManager.Models.UserDetail

@{
    ViewData["Title"] = "Edit user informations";
}

<section class="contact_area section_gap">
    <div class="container">
        <div class="row justify-content-center align-items-center flex-column">
            <div class="col-sm-12">
                <h2 class="title_color">Edit user details</h2>
            </div>
            <div class="col-lg-6 col-sm-10">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="UserDetailId" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="SecondName" class="control-label"></label>
                        <input asp-for="SecondName" class="form-control" />
                        <span asp-validation-for="SecondName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Region" class="control-label"></label>
                        <input asp-for="Region" class="form-control" />
                        <span asp-validation-for="Region" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PostCode" class="control-label"></label>
                        <input asp-for="PostCode" class="form-control" />
                        <span asp-validation-for="PostCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input asp-for="UserId" type="hidden" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn theme_btn button_hover" />
                    </div>
                </form>
            </div>
            <div class="col-sm-12">
                <a asp-controller="Home" asp-action="Index" class="button_hover theme_btn_two">Back to list</a>
            </div>
        </div>
    </div>
</section>

MeetingManagerMvc/Views/UserDetailClient/Index.cshtml
@model MeetingManager.Models.UserDetail

@{
    ViewData["Title"] = "User details";

    string ValidEmptyString(string text){
        if(text == "")
        {
            return "-";
        }
        return text;
    }
}

<section class="contact_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <nav class="nav nav-borders mb-3" style="border-bottom: 1px solid lightgray;">
                    <a asp-controller="UserDetailClient" asp-action="Index" class="nav-link active">Profile </a>
                    <a asp-controller="OrderClient" asp-action="List" asp-route-id="@Model.UserId" class="nav-link">Orders </a>
                    <a asp-controller="DashboardClient" asp-action="Index" class="nav-link">Offers </a>
                </nav>
            </div>
            <div class="col-lg-12">
                <div class="row">
                    <div class="col-xl-4">
                        <!-- Profile picture card-->
                        <div class="card mb-4 mb-xl-0">
                            <div class="card-header">Profile Picture</div>
                            <div class="card-body text-center">
                                <img class="img-account-profile rounded-circle mb-2" src="http://bootdey.com/img/Content/avatar/avatar1.png" alt="">
                                <a asp-controller="UserClient" asp-action="Edit" asp-route-id="@Model.UserId">Edit access data <i class="fas fa-edit"></i></a><br />
                                <a asp-action="Edit" asp-route-id="@Model.UserId">Edit contact data <i class="fas fa-user-edit"></i></a><br />
                                <a asp-controller="UserClient" asp-action="Delete" asp-route-id="@Model.UserId">Delete account <i class="fas fa-user-minus"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-8">
                        <!-- Account details card-->
                        <div class="card mb-4">
                            <div class="card-header">Account Details</div>
                            <div class="card-body">
                                <form>
                                    <div class="row gx-3 mb-3">
                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputFirstName">First name</label>
                                            <input class="form-control" id="inputFirstName" type="text" value="@ValidEmptyString(Model.Name)" disabled>
                                        </div>
                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputFirstName">Second name (optional)</label>
                                            <input class="form-control" id="inputFirstName" type="text" value="@ValidEmptyString(Model.SecondName)" disabled>
                                        </div>
                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputLastName">Last name</label>
                                            <input class="form-control" id="inputLastName" type="text" value="@ValidEmptyString(Model.LastName)" disabled>
                                        </div>
                                    </div>
                                    <div class="row gx-3 mb-3">
                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputOrgName">Country</label>
                                            <input class="form-control" id="inputOrgName" type="text" value="@ValidEmptyString(Model.Country)" disabled>
                                        </div>

                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputOrgName">City</label>
                                            <input class="form-control" id="inputOrgName" type="text" value="@ValidEmptyString(Model.City)" disabled>
                                        </div>

                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputOrgName">Region</label>
                                            <input class="form-control" id="inputOrgName" type="text" value="@ValidEmptyString(Model.Region)" disabled>
                                        </div>
                                    </div>
                                    <div class="row gx-3 mb-3">
                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputLocation">Postal code</label>
                                            <input class="form-control" id="inputLocation" type="text" value="@ValidEmptyString(Model.PostCode)" disabled>
                                        </div>

                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputEmailAddress">Address</label>
                                            <input class="form-control" id="inputEmailAddress" type="text" value="@ValidEmptyString(Model.Address)" disabled>
                                        </div>

                                        <div class="col-md-4">
                                            <label class="small mb-1" for="inputPhone">Phone number</label>
                                            <input class="form-control" id="inputPhone" type="tel" placeholder="Enter your phone number" value="@ValidEmptyString(Model.Phone)" disabled>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 mt-3">
                <a asp-controller="OfferClient" asp-action="Index">Back to offerts List</a>
            </div>
        </div>
    </div>
</section>